name: CI/CD Pipeline

on:
 push:
   branches: [ "main" ]

jobs:
 build-and-deploy:
   runs-on: ubuntu-latest

   steps:
  
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Set up Docker
     uses: docker/setup-buildx-action@v3

   - name: Build Docker Image
     run: docker build -t my-backend-app ./Backend/Experiment-13

   - name: Run Container
     run: docker run -d -p 5000:5000 my-backend-app
